# Universidade de Brasília
## Programa de Pós-Graduação em Computação Aplicada
## Mestrato Profissional em Computação Aplicada
### Mineração de Dados
#### Professor: Marcelo Ladeira
#### Alunos: 
##### 22000xxxx - Alisson Melo Rios
##### 22000xxxx - Filipe Oliveira da Silva
##### 220005559 - Luís Eduardo Barreiro de Jesus

## PREPARAÇÃO DO AMBIENTE DE PROCESSAMENTO

In [1]:
# Preparação do Ambiente
## Seção de bibliotecas
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
from mlxtend.frequent_patterns import apriori, association_rules

import json
import datetime 

import folium
from folium.plugins import HeatMap, HeatMapWithTime, MarkerCluster

from apyori import apriori

## MANIPULAÇÃO DE DADOS

Nesta seção, faz-se a manipulação dos dados de forma a se gerar as informações de acordo com a necessidade da análise dos dados.

### Colunas do Dataframe

Nesta subseção, trabalha-se a identificação de subgrupos de dados carregados de registros de Acidentes da PRF.

In [2]:
## Criar um dataframe vazio para concatenação a partir da carga de um dos arquivos
df1 = pd.read_csv("./dados/acidentes2021.csv", sep=";", dtype={'br': 'str', 'id': 'int64'}, decimal=",", encoding="latin1", nrows=1)

# Extract column names into a list
column_names = [x for x in df1.columns]

# Create empty DataFrame with those column names
df = pd.DataFrame(columns=column_names)

# Apagar o DataFrame 
del df1
#df1

# Imprimir para verificar se o DataFrame está vazio
df

Empty DataFrame
Columns: [id, pesid, data_inversa, dia_semana, horario, uf, br, km, municipio, causa_acidente, tipo_acidente, classificacao_acidente, fase_dia, sentido_via, condicao_metereologica, tipo_pista, tracado_via, uso_solo, id_veiculo, tipo_veiculo, marca, ano_fabricacao_veiculo, tipo_envolvido, estado_fisico, idade, sexo, ilesos, feridos_leves, feridos_graves, mortos, latitude, longitude, regional, delegacia, uop]
Index: []

[0 rows x 35 columns]

In [3]:
# Constantes
## Colunas do Dataframe e operações tipo 1
## sumarização da quantidade de pessoas e estado em consequência do acidente
col_oper1 = {'id':'count', 'pessoas':'sum', 'mortos':'sum', 'feridos_leves':'sum', 'feridos_graves':'sum', 'veiculos':'sum'}

## Colunas do Dataframe e operações tipo 2
col_oper2 = {'id':'count', 'mortos':'sum', 'feridos_leves':'sum', 'feridos_graves':'sum', 'veiculos':'sum'}

#------------------------------------------------------------
# Para a geração de subdatasets
#------------------------------------------------------------
## colunas dos registros de acidentes 
col_acidentes = ['id',  
                'data_inversa', 
                'dia_semana', 
                'horario', 
                'uf', 
                'br',
                'km',
                'kmint',
                'municipio', 
                'causa_acidente', 
                'tipo_acidente',
                'classificacao_acidente', 
                'fase_dia', 
                'sentido_via',
                'condicao_metereologica', 
                'tipo_pista',
                'tracado_via', 
                'ilesos',
                'feridos_leves', 
                'feridos_graves', 
                'mortos',
                'uso_solo',
                'latitude', 
                'longitude',
                'regional', 
                'delegacia', 
                'uop',
                'ano_mes',
                'ano',
                'mes']

## colunas dos registros de veículos
col_veiculos = ['id',
                'id_veiculo', 
                'tipo_veiculo', 
                'marca', 
                'ano_fabricacao_veiculo',
                'ilesos',
                'feridos_leves', 
                'feridos_graves', 
                'mortos',
                'ano_mes',
                'ano',
                'mes']

## colunas dos registros de pessoas
col_pessoas =  ['id',
                'id_veiculo',
                'pesid',
                'tipo_envolvido', 
                'estado_fisico', 
                'idade', 
                'sexo']

### Carga do(s) arquivo(s) de registro de acidentes

A fonte de dados está disponível no sítio eletrônico de Dados Abertos da Polícia Rodoviária Federal, Órgão responsável, dentro outras, do patrulhamento das rodovias (CF 1988, art. 144, § 2º).

Link: https://www.gov.br/prf/pt-br/acesso-a-informacao/dados-abertos/dados-abertos-acidentes

In [4]:
# função para carregar os arquivos de acidentes de trânsito
def _carrega_arquivos(_ano, df, _separador, _enconding):
    print(f"Início da carga do arquivo de acidentes de {_ano}....", datetime.datetime.today())
    dftmp = pd.read_csv(f"./dados/acidentes{_ano}.csv", dtype={'br': 'str', 'id': 'int64'}, encoding=_enconding, decimal=",", sep=_separador, parse_dates=True)
    dftmp = dftmp.loc[(dftmp['br']=='40')]
    dftmp['data_inversa']= pd.to_datetime(dftmp['data_inversa'])
    dftmp['causa_acidente'] = dftmp['causa_acidente'].str.upper()
    dftmp['tipo_acidente'] = dftmp['tipo_acidente'].str.upper()
    dftmp["km"] = pd.to_numeric(dftmp["km"])
    # Transformar o campo no tipo Datetime
    dftmp["data_inversa"] = pd.to_datetime(dftmp["data_inversa"])
    # Criar campo ano
    dftmp["ano"] = dftmp["data_inversa"].dt.year
    # Criar campo mês
    dftmp["mes"] = dftmp["data_inversa"].dt.month
    # Campo com ano e mês
    dftmp["ano_mes"] = dftmp['data_inversa'].dt.strftime('%B/%Y')
    # Manipulando o campo br
    dftmp["br"] = "BR-" + dftmp["br"].str.zfill(3)
    # Manipulando o campo KM para criar um campo KM de valor inteiro para posteriormente incluir
    dftmp["kmint"] = dftmp["km"].astype(int)
#df.astype({'kmint':'int'})
    df = pd.concat([df, dftmp], axis=0)
    print(f"Fim da carga do arquivo de acidentes de {_ano}....", datetime.datetime.today())
    print("Total de registros carregadas da BR-040...", len(dftmp))
    del dftmp
    return df

# Definir função para atualização do lat e long vazio
def _find_mean_lat_long():
    xx = 1

In [5]:
# Realização da carga do arquivos para dataframe
# parâmetros: ano dos regitros, dataframe, separador, encoding
df = _carrega_arquivos("2007", df, ",","latin1")
df = _carrega_arquivos("2008", df, ",","latin1")
df = _carrega_arquivos("2009", df, ",","latin1")
df = _carrega_arquivos("2010", df, ",","latin1")
df = _carrega_arquivos("2011", df, ",","latin1")
df = _carrega_arquivos("2012", df, ",","latin1")
df = _carrega_arquivos("2013", df, ",","latin1")
df = _carrega_arquivos("2014", df, ",","latin1")
df = _carrega_arquivos("2015", df, ",","latin1")
df = _carrega_arquivos("2016", df, ";","latin1")
df = _carrega_arquivos("2017", df, ";","latin1")
df = _carrega_arquivos("2018", df, ";","latin1")
df = _carrega_arquivos("2019", df, ";","latin1")
df = _carrega_arquivos("2020", df, ";","utf-8")
df = _carrega_arquivos("2021", df, ";","latin1")

Início da carga do arquivo de acidentes de 2007.... 2022-09-15 23:41:08.256131
Fim da carga do arquivo de acidentes de 2007.... 2022-09-15 23:41:09.589285
Total de registros carregadas da BR-040... 14024
Início da carga do arquivo de acidentes de 2008.... 2022-09-15 23:41:09.590491
Fim da carga do arquivo de acidentes de 2008.... 2022-09-15 23:41:11.005821
Total de registros carregadas da BR-040... 15176
Início da carga do arquivo de acidentes de 2009.... 2022-09-15 23:41:11.008259
Fim da carga do arquivo de acidentes de 2009.... 2022-09-15 23:41:12.387820
Total de registros carregadas da BR-040... 16377
Início da carga do arquivo de acidentes de 2010.... 2022-09-15 23:41:12.391770
Fim da carga do arquivo de acidentes de 2010.... 2022-09-15 23:41:14.107611
Total de registros carregadas da BR-040... 20056
Início da carga do arquivo de acidentes de 2011.... 2022-09-15 23:41:14.113709
Fim da carga do arquivo de acidentes de 2011.... 2022-09-15 23:41:15.848377
Total de registros carregadas da BR-040... 21233
Início da carga do arquivo de acidentes de 2012.... 2022-09-15 23:41:15.856309
Fim da carga do arquivo de acidentes de 2012.... 2022-09-15 23:41:17.472102
Total de registros carregadas da BR-040... 19739
Início da carga do arquivo de acidentes de 2013.... 2022-09-15 23:41:17.481906
Fim da carga do arquivo de acidentes de 2013.... 2022-09-15 23:41:19.071991
Total de registros carregadas da BR-040... 19847
Início da carga do arquivo de acidentes de 2014.... 2022-09-15 23:41:19.083817
Fim da carga do arquivo de acidentes de 2014.... 2022-09-15 23:41:20.575583
Total de registros carregadas da BR-040... 17058
Início da carga do arquivo de acidentes de 2015.... 2022-09-15 23:41:20.589442
Fim da carga do arquivo de acidentes de 2015.... 2022-09-15 23:41:21.726367
Total de registros carregadas da BR-040... 12206
Início da carga do arquivo de acidentes de 2016.... 2022-09-15 23:41:21.741498
Fim da carga do arquivo de acidentes de 2016.... 2022-09-15 23:41:22.476734
Total de registros carregadas da BR-040... 10015
Início da carga do arquivo de acidentes de 2017.... 2022-09-15 23:41:22.492174
Fim da carga do arquivo de acidentes de 2017.... 2022-09-15 23:41:23.372288
Total de registros carregadas da BR-040... 9489
Início da carga do arquivo de acidentes de 2018.... 2022-09-15 23:41:23.389396
Fim da carga do arquivo de acidentes de 2018.... 2022-09-15 23:41:24.090541
Total de registros carregadas da BR-040... 7766
Início da carga do arquivo de acidentes de 2019.... 2022-09-15 23:41:24.107752
Fim da carga do arquivo de acidentes de 2019.... 2022-09-15 23:41:24.807198
Total de registros carregadas da BR-040... 7817
Início da carga do arquivo de acidentes de 2020.... 2022-09-15 23:41:24.825317
Fim da carga do arquivo de acidentes de 2020.... 2022-09-15 23:41:25.414381
Total de registros carregadas da BR-040... 7110
Início da carga do arquivo de acidentes de 2021.... 2022-09-15 23:41:25.433268
Fim da carga do arquivo de acidentes de 2021.... 2022-09-15 23:41:26.117549
Total de registros carregadas da BR-040... 7256

In [6]:
df

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,...,longitude,regional,delegacia,uop,nacionalidade,naturalidade,ano,mes,ano_mes,kmint
33,173740,446496,2007-01-01 00:00:00,Segunda,00:40:00,MG,BR-040,637.0,CONSELHEIRO LAFAIETE,ANIMAIS NA PISTA,...,NaN,NaN,NaN,NaN,Brasil,Conselheiro Lafaiete,2007.0,1.0,January/2007,637.0
37,173743,446500,2007-01-01 00:00:00,Segunda,02:55:00,RJ,BR-040,119.0,DUQUE DE CAXIAS,VELOCIDADE INCOMPATÍVEL,...,NaN,NaN,NaN,NaN,Brasil,Não Informado,2007.0,1.0,January/2007,119.0
38,173743,446503,2007-01-01 00:00:00,Segunda,02:55:00,RJ,BR-040,119.0,DUQUE DE CAXIAS,VELOCIDADE INCOMPATÍVEL,...,NaN,NaN,NaN,NaN,Brasil,Não Informado,2007.0,1.0,January/2007,119.0
43,173750,446515,2007-01-01 00:00:00,Segunda,04:56:00,MG,BR-040,45.0,PARACATU,VELOCIDADE INCOMPATÍVEL,...,NaN,NaN,NaN,NaN,Brasil,Não Informado,2007.0,1.0,January/2007,45.0
76,173790,446635,2007-01-01 00:00:00,Segunda,01:43:00,MG,BR-040,699.9,BARBACENA,OUTRAS,...,NaN,NaN,NaN,NaN,Brasil,Não Informado,2007.0,1.0,January/2007,699.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150749,459999,993477.0,2021-12-06 00:00:00,segunda-feira,07:05:00,DF,BR-040,5.0,BRASILIA,MANOBRA DE MUDANÇA DE FAIXA,...,-47.980541,SPRF-DF,DEL01-DF,UOP01-DEL01-DF,NaN,NaN,2021.0,12.0,December/2021,5.0
150750,459999,993476.0,2021-12-06 00:00:00,segunda-feira,07:05:00,DF,BR-040,5.0,BRASILIA,MANOBRA DE MUDANÇA DE FAIXA,...,-47.980541,SPRF-DF,DEL01-DF,UOP01-DEL01-DF,NaN,NaN,2021.0,12.0,December/2021,5.0
150753,460189,994116.0,2021-05-14 00:00:00,sexta-feira,18:30:00,MG,BR-040,510.0,RIBEIRAO DAS NEVES,CONDUTOR DEIXOU DE MANTER DISTÂNCIA DO VEÍCULO...,...,-44.123219,SPRF-MG,DEL01-MG,UOP02-DEL01-MG,NaN,NaN,2021.0,5.0,May/2021,510.0
150754,460189,994115.0,2021-05-14 00:00:00,sexta-feira,18:30:00,MG,BR-040,510.0,RIBEIRAO DAS NEVES,CONDUTOR DEIXOU DE MANTER DISTÂNCIA DO VEÍCULO...,...,-44.123219,SPRF-MG,DEL01-MG,UOP02-DEL01-MG,NaN,NaN,2021.0,5.0,May/2021,510.0
150755,460189,994114.0,2021-05-14 00:00:00,sexta-feira,18:30:00,MG,BR-040,510.0,RIBEIRAO DAS NEVES,CONDUTOR DEIXOU DE MANTER DISTÂNCIA DO VEÍCULO...,...,-44.123219,SPRF-MG,DEL01-MG,UOP02-DEL01-MG,NaN,NaN,2021.0,5.0,May/2021,510.0

In [7]:
# Criar dataframe com o trecho da BR-040

# - Condições:
# -- DF: KM 000 até km 8,400 
# -- GO: Todo o trecho
# -- MG: KM 000 até KM 773


#df = pd.concat([df[(df.uf == 'DF')&(df.km > 0)&(df.km < 8.4)], df[(df.uf == 'GO')], df[(df.uf == 'MG')&(df.km > 0)&(df.km < 773)], df[(df.classificacao_acidente != 'Sem Vítimas')]], axis=0)
df = pd.concat([df[(df.uf == 'DF')&(df.km > 0)&(df.km < 8.4)], df[(df.uf == 'GO')], df[(df.uf == 'MG')&(df.km > 0)&(df.km < 774)]], axis=0)
                
#df = df.query("classificacao_acidente == 'Com Vítimas Feridas' or classificacao_acidente == 'Com Vítimas Fatais'")
#df = df.query("classificacao_acidente != 'SEM VÍTIMAS'")
#Com Vítimas Feridas, Sem Vítimas, Com Vítimas Fatais
df

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,...,longitude,regional,delegacia,uop,nacionalidade,naturalidade,ano,mes,ano_mes,kmint
1749,175013,450607,2007-03-01 00:00:00,Quarta,19:10:00,DF,BR-040,5.8,BRASILIA,OUTRAS,...,NaN,NaN,NaN,NaN,Brasil,Não Informado,2007.0,3.0,March/2007,5.0
1750,175013,450610,2007-03-01 00:00:00,Quarta,19:10:00,DF,BR-040,5.8,BRASILIA,OUTRAS,...,NaN,NaN,NaN,NaN,Brasil,Brasilia,2007.0,3.0,March/2007,5.0
1751,175013,450618,2007-03-01 00:00:00,Quarta,19:10:00,DF,BR-040,5.8,BRASILIA,OUTRAS,...,NaN,NaN,NaN,NaN,Brasil,Brasilia,2007.0,3.0,March/2007,5.0
4017,176396,454898,2007-01-01 00:00:00,Segunda,23:00:00,DF,BR-040,4.4,BRASILIA,DEFEITO NA VIA,...,NaN,NaN,NaN,NaN,Brasil,Brasileira,2007.0,1.0,January/2007,4.0
4018,176396,454902,2007-01-01 00:00:00,Segunda,23:00:00,DF,BR-040,4.4,BRASILIA,DEFEITO NA VIA,...,NaN,NaN,NaN,NaN,Brasil,Brasileira,2007.0,1.0,January/2007,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150681,455947,983811.0,2021-11-02 00:00:00,terça-feira,20:30:00,MG,BR-040,194.9,JOAO PINHEIRO,DEIXAR DE ACIONAR O FAROL DA MOTOCICLETA (OU S...,...,-45.86067,SPRF-MG,DEL14-MG,UOP02-DEL14-MG,NaN,NaN,2021.0,11.0,November/2021,194.0
150715,457815,988123.0,2021-12-25 00:00:00,sábado,06:00:00,MG,BR-040,530.2,BELO HORIZONTE,AUSÊNCIA DE REAÇÃO DO CONDUTOR,...,-44.033568,SPRF-MG,DEL01-MG,UOP02-DEL01-MG,NaN,NaN,2021.0,12.0,December/2021,530.0
150753,460189,994116.0,2021-05-14 00:00:00,sexta-feira,18:30:00,MG,BR-040,510.0,RIBEIRAO DAS NEVES,CONDUTOR DEIXOU DE MANTER DISTÂNCIA DO VEÍCULO...,...,-44.123219,SPRF-MG,DEL01-MG,UOP02-DEL01-MG,NaN,NaN,2021.0,5.0,May/2021,510.0
150754,460189,994115.0,2021-05-14 00:00:00,sexta-feira,18:30:00,MG,BR-040,510.0,RIBEIRAO DAS NEVES,CONDUTOR DEIXOU DE MANTER DISTÂNCIA DO VEÍCULO...,...,-44.123219,SPRF-MG,DEL01-MG,UOP02-DEL01-MG,NaN,NaN,2021.0,5.0,May/2021,510.0
150755,460189,994114.0,2021-05-14 00:00:00,sexta-feira,18:30:00,MG,BR-040,510.0,RIBEIRAO DAS NEVES,CONDUTOR DEIXOU DE MANTER DISTÂNCIA DO VEÍCULO...,...,-44.123219,SPRF-MG,DEL01-MG,UOP02-DEL01-MG,NaN,NaN,2021.0,5.0,May/2021,510.0

In [8]:
#quebra

### Dataframe dos Acidentes

In [9]:
# Criar Dataframe com os registros de acidentes (a estrutura do arquivo tem repetição nesses campos)
dfacid = df[col_acidentes]
# Total de registros antes de retirada das duplicações
len(dfacid)

140402

OBS:
- O total de registros do período é 150.919

In [10]:
# retirar as duplicações do acidentes
dfacid = dfacid.drop_duplicates(subset=['id'], keep='last')
# Total de registros únicos
len(dfacid)

63109

In [11]:
#query para buscar todos os registros de longitude is null
df1 = dfacid.query("not (longitude >= 0 or longitude <0)")
#df1 = df1.loc[:,['uf','kmint']]
df1

,id,data_inversa,dia_semana,horario,uf,br,km,kmint,municipio,causa_acidente,...,mortos,uso_solo,latitude,longitude,regional,delegacia,uop,ano_mes,ano,mes
1751,175013,2007-03-01 00:00:00,Quarta,19:10:00,DF,BR-040,5.8,5.0,BRASILIA,OUTRAS,...,NaN,Rural,NaN,NaN,NaN,NaN,NaN,March/2007,2007.0,3.0
4018,176396,2007-01-01 00:00:00,Segunda,23:00:00,DF,BR-040,4.4,4.0,BRASILIA,DEFEITO NA VIA,...,NaN,Urbano,NaN,NaN,NaN,NaN,NaN,January/2007,2007.0,1.0
4849,176880,2007-08-01 00:00:00,Segunda,14:30:00,DF,BR-040,3.0,3.0,BRASILIA,DEFEITO MECÂNICO EM VEÍCULO,...,NaN,Urbano,NaN,NaN,NaN,NaN,NaN,August/2007,2007.0,8.0
4920,176914,2007-08-01 00:00:00,Segunda,14:30:00,DF,BR-040,3.0,3.0,BRASILIA,OUTRAS,...,NaN,Urbano,NaN,NaN,NaN,NaN,NaN,August/2007,2007.0,8.0
5700,177406,2007-03-01 00:00:00,Quarta,15:45:00,DF,BR-040,2.0,2.0,BRASILIA,FALTA DE ATENÇÃO,...,NaN,Urbano,NaN,NaN,NaN,NaN,NaN,March/2007,2007.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215900,83529738,2016-12-31 00:00:00,Sábado,10:00:00,MG,BR-040,310.0,310.0,TRES MARIAS,FALTA DE ATENÇÃO,...,NaN,Rural,NaN,NaN,NaN,NaN,NaN,December/2016,2016.0,12.0
216078,83529484,2016-12-31 00:00:00,Sábado,16:00:00,MG,BR-040,432.0,432.0,PARAOPEBA,INGESTÃO DE ÁLCOOL,...,NaN,Rural,NaN,NaN,NaN,NaN,NaN,December/2016,2016.0,12.0
216108,83529610,2016-12-31 00:00:00,Sábado,16:33:00,MG,BR-040,524.0,524.0,CONTAGEM,OUTRAS,...,NaN,Urbano,NaN,NaN,NaN,NaN,NaN,December/2016,2016.0,12.0
216147,83529357,2016-12-31 00:00:00,Sábado,19:00:00,MG,BR-040,550.0,550.0,NOVA LIMA,VELOCIDADE INCOMPATÍVEL,...,NaN,Urbano,NaN,NaN,NaN,NaN,NaN,December/2016,2016.0,12.0
216200,83529658,2016-12-31 00:00:00,Sábado,20:40:00,MG,BR-040,498.3,498.0,ESMERALDAS,INGESTÃO DE ÁLCOOL,...,NaN,Urbano,NaN,NaN,NaN,NaN,NaN,December/2016,2016.0,12.0

In [12]:
# latitude e longitude para 
df2 = dfacid.groupby(['uf','kmint']).agg({'latitude':'mean', 'longitude':'mean'})
df2 = df2.reset_index()
df2

     uf  kmint   latitude  longitude
0    DF    0.0 -15.981352 -47.989304
1    DF    1.0 -15.983561 -47.985495
2    DF    2.0 -15.996914 -47.985667
3    DF    3.0 -16.004644 -47.984465
4    DF    4.0 -16.014475 -47.981882
..   ..    ...        ...        ...
929  MG  769.0 -21.608658 -43.456136
930  MG  770.0 -21.610662 -43.453494
931  MG  771.0 -21.621509 -43.450251
932  MG  772.0 -21.633277 -43.443716
933  MG  773.0 -21.643959 -43.438177

[934 rows x 4 columns]

In [13]:
# merge para atualização dos campos latitude e longitude
df3 = pd.merge(df1, df2, how = 'inner', on = ['uf','kmint'])
df3 = df3.drop(['latitude_x', 'longitude_x'], axis=1)
df3.rename(columns={'latitude_y':'latitude', 'longitude_y':'longitude'}, inplace=True)
df3

,id,data_inversa,dia_semana,horario,uf,br,km,kmint,municipio,causa_acidente,...,mortos,uso_solo,regional,delegacia,uop,ano_mes,ano,mes,latitude,longitude
0,175013,2007-03-01 00:00:00,Quarta,19:10:00,DF,BR-040,5.8,5.0,BRASILIA,OUTRAS,...,NaN,Rural,NaN,NaN,NaN,March/2007,2007.0,3.0,-15.971308,-48.402776
1,182070,2007-01-21 00:00:00,Domingo,22:40:00,DF,BR-040,5.2,5.0,BRASILIA,FALTA DE ATENÇÃO,...,NaN,Rural,NaN,NaN,NaN,January/2007,2007.0,1.0,-15.971308,-48.402776
2,199330,2007-04-03 00:00:00,Domingo,16:00:00,DF,BR-040,5.1,5.0,BRASILIA,OUTRAS,...,NaN,Urbano,NaN,NaN,NaN,April/2007,2007.0,4.0,-15.971308,-48.402776
3,240356,2007-06-13 00:00:00,Quarta,14:30:00,DF,BR-040,5.7,5.0,BRASILIA,OUTRAS,...,NaN,Urbano,NaN,NaN,NaN,June/2007,2007.0,6.0,-15.971308,-48.402776
4,242376,2007-06-18 00:00:00,Segunda,08:45:00,DF,BR-040,5.6,5.0,BRASILIA,DEFEITO MECÂNICO EM VEÍCULO,...,NaN,Urbano,NaN,NaN,NaN,June/2007,2007.0,6.0,-15.971308,-48.402776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50993,83131470,2014-01-17 00:00:00,Sexta,17:50:00,MG,BR-040,336.8,336.0,FELIXLANDIA,FALTA DE ATENÇÃO,...,NaN,Rural,NaN,NaN,NaN,January/2014,2014.0,1.0,-18.624637,-45.005686
50994,83322329,2015-02-23 00:00:00,Segunda,16:00:00,MG,BR-040,336.3,336.0,FELIXLANDIA,VELOCIDADE INCOMPATÍVEL,...,NaN,Rural,NaN,NaN,NaN,February/2015,2015.0,2.0,-18.624637,-45.005686
50995,83478457,2016-06-30 00:00:00,Quinta,07:00:00,MG,BR-040,336.5,336.0,FELIXLANDIA,VELOCIDADE INCOMPATÍVEL,...,NaN,Rural,NaN,NaN,NaN,June/2016,2016.0,6.0,-18.624637,-45.005686
50996,83384899,2015-10-08 00:00:00,Segunda,22:15:00,MG,BR-040,163.8,163.0,JOAO PINHEIRO,FALTA DE ATENÇÃO,...,NaN,Rural,NaN,NaN,NaN,October/2015,2015.0,10.0,NaN,NaN
50997,83498079,2016-12-09 00:00:00,Segunda,12:45:00,MG,BR-040,206.0,206.0,JOAO PINHEIRO,DESOBEDIÊNCIA À SINALIZAÇÃO,...,NaN,Rural,NaN,NaN,NaN,December/2016,2016.0,12.0,-17.994535,-45.764015

In [14]:
# retirar as linhas do dataframe de acidentes que tem latitude ou longitude vazia NaN
#dfacid.drop(dfacid.iloc(dfacid.query("not (longitude >= 0 or longitude <0)")))
dfacid.dropna(subset=['latitude', 'longitude'], inplace=True)

In [15]:
# Formar o último 
dfacid = pd.concat([df3, dfacid], axis=0)

In [16]:
len(dfacid)

63109

OBS:
- O total de acidentes do período é de 64.536;

### Estatística Descritiva dos dados de Acidentes

In [17]:
# imprimir os dados para verificação visual
dfacid.head(5)

,id,data_inversa,dia_semana,horario,uf,br,km,kmint,municipio,causa_acidente,...,mortos,uso_solo,regional,delegacia,uop,ano_mes,ano,mes,latitude,longitude
0,175013,2007-03-01 00:00:00,Quarta,19:10:00,DF,BR-040,5.8,5.0,BRASILIA,OUTRAS,...,NaN,Rural,NaN,NaN,NaN,March/2007,2007.0,3.0,-15.971308,-48.402776
1,182070,2007-01-21 00:00:00,Domingo,22:40:00,DF,BR-040,5.2,5.0,BRASILIA,FALTA DE ATENÇÃO,...,NaN,Rural,NaN,NaN,NaN,January/2007,2007.0,1.0,-15.971308,-48.402776
2,199330,2007-04-03 00:00:00,Domingo,16:00:00,DF,BR-040,5.1,5.0,BRASILIA,OUTRAS,...,NaN,Urbano,NaN,NaN,NaN,April/2007,2007.0,4.0,-15.971308,-48.402776
3,240356,2007-06-13 00:00:00,Quarta,14:30:00,DF,BR-040,5.7,5.0,BRASILIA,OUTRAS,...,NaN,Urbano,NaN,NaN,NaN,June/2007,2007.0,6.0,-15.971308,-48.402776
4,242376,2007-06-18 00:00:00,Segunda,08:45:00,DF,BR-040,5.6,5.0,BRASILIA,DEFEITO MECÂNICO EM VEÍCULO,...,NaN,Urbano,NaN,NaN,NaN,June/2007,2007.0,6.0,-15.971308,-48.402776

SUGESTÕES DE PERGUNTAS:
- Relação de causa do acidente x tipo do acidente x horario do acidente x condição meteorologica x tipo de pista x traçado da via x uso do solo x dia da semana com a mortalidade dos acidentes?
- Relação de tipos de veículos x mortalidade dos acidentes?
- Escolher um trecho de rodovia concedida para analisar. Exemplo: BR-040 DF até Juiz de Fora;

#### Domínios do acidente

Exemplo   | Valor do exemplo
--------- | ------
causa_acidente | Reação tardia ou ineficiente do condutor ,Velocidade Incompatível ,Demais falhas mecânicas ou elétricas ,Entrada inopinada do pedestre ,Condutor Dormindo ,Frear bruscamente ,Acessar a via sem observar a presença dos outros veículos ,Chuva ,Ausência de reação do condutor ,Pedestre andava na pista ,Problema com o freio ,Carga excessiva e/ou mal acondicionada ,Ingestão de álcool pelo condutor ,Acostamento em desnível ,Ultrapassagem Indevida ,Mal súbito do condutor ,Curva acentuada ,Avarias e/ou desgaste excessivo no pneu ,Acumulo de água sobre o pavimento ,Condutor deixou de manter distância do veículo da frente ,Pedestre cruzava a pista fora da faixa ,Falta de elemento de contenção que evite a saída do leito carroçável ,Manobra de mudança de faixa ,Demais falhas na via ,Condutor usando celular ,Pista Escorregadia ,Ingestão de álcool ou de substâncias psicoativas pelo pedestre ,Obstrução na via ,Ingestão de álcool e/ou substâncias psicoativas pelo pedestre ,Acumulo de óleo sobre o pavimento ,Ingestão de substâncias psicoativas pelo condutor ,Transitar na contramão ,Iluminação deficiente ,Pista esburacada ,Conversão proibida ,Afundamento ou ondulação no pavimento ,Animais na Pista ,Demais Fenômenos da natureza ,Transitar no acostamento ,Desrespeitar a preferência no cruzamento ,Falta de acostamento ,Objeto estático sobre o leito carroçável ,Pista em desnível ,Estacionar ou parar em local proibido ,Área urbana sem a presença de local apropriado para a travessia de pedestres ,Desvio temporário ,Declive acentuado ,Obras na pista ,Ausência de sinalização ,Acumulo de areia ou detritos sobre o pavimento ,Problema na suspensão ,Acesso irregular ,Retorno proibido ,Sinalização mal posicionada ,Deficiência do Sistema de Iluminação/Sinalização ,Faixas de trânsito com largura insuficiente ,Restrição de visibilidade em curvas horizontais ,Neblina ,Fumaça ,Faróis desregulados ,Sistema de drenagem ineficiente ,Restrição de visibilidade em curvas verticais ,Condutor desrespeitou a iluminação vermelha do semáforo ,Trafegar com motocicleta (ou similar) entre as faixas ,Redutor de velocidade em desacordo ,Deixar de acionar o farol da motocicleta (ou similar) ,Transitar na calçada ,Semáforo com defeito ,Participar de racha ,Sinalização encoberta ,Modificação proibida
tipo_acidente | Tombamento ,Incêndio ,Atropelamento de Pedestre ,Saída de leito carroçável ,Capotamento ,Colisão com objeto ,Colisão traseira ,Derramamento de carga ,Colisão lateral ,Eventos atípicos ,Colisão frontal ,Colisão lateral sentido oposto ,Colisão lateral mesmo sentido ,Atropelamento de Animal ,Colisão transversal ,Engavetamento ,Queda de ocupante de veículo
classificacao_acidente | Com Vítimas Feridas, Sem Vítimas, Com Vítimas Fatais
fase_dia | Amanhecer, Pleno dia, Plena Noite, Anoitecer
sentido_via | Crescente, Decrescente, Não Informado
condicao_metereologica | Nublado, Céu Claro, Chuva, Ignorado, Sol, Garoa/Chuvisco, Nevoeiro/Neblina, Vento, Neve, Granizo
tipo_pista | Dupla, Simples, Múltipla
tracado_via | Curva, Reta, Não Informado, Desvio Temporário, Retorno Regulamentado, Ponte, Interseção de vias, Rotatória, Túnel, Viaduto
uso_solo | Não, Sim


## Dados abertos antt

https://dados.antt.gov.br/dataset/trecho-concedido/resource/2de5d294-13fc-4ff1-aa6d-60306e3eb492

concessionaria;ano_do_pnv_snv;tipo_de_rodovia;rodovia;uf;km_m_inicial;km_m_final;direcao;sentido

VIA 040;2010;Federal;BR-40;DF;0,000;8,400;Sul;Crescente

VIA 040;2010;Federal;BR-40;DF;8,400;0,000;Norte;Decrescente

VIA 040;2010;Federal;BR-40;GO;0,000;157,300;Sul;Crescente

VIA 040;2010;Federal;BR-40;GO;157,300;0,000;Norte;Decrescente

VIA 040;2010;Federal;BR-40;MG;0,000;773,500;Sul;Crescente

VIA 040;2010;Federal;BR-40;MG;773,500;0,000;Norte;Decrescente

In [18]:
dictio = {'id':'count', 'ilesos':'sum','feridos_leves':'sum','feridos_graves':'sum', 'mortos':'sum'}

# Análise estatística dos dados de acidentes
def _acidentes(df, aggr_field, dicio ):
    ## Acidentes por ano_mes
    #dfagg_acid = dfacid.groupby(['causa_acidente']).agg({'id':'count', 'ilesos':'sum','feridos_leves':'sum','feridos_graves':'sum', 'mortos':'sum'})
    df = df.groupby(aggr_field).agg(dicio)
    # Altera o nome da coluna id para qtd - count(id)
    df.rename(columns={'id':'qtd'}, inplace=True)
    df['percentual_mortalidade'] = df['mortos'] / df['qtd'] * 100
    df.reset_index(inplace=True)
    df = df.sort_values(by=['percentual_mortalidade'],ascending=False)
    
    return df
# imprimir
#dfagg_acid


def _acidente_pessoas(df, aggr_field, dict_pess):
    print(aggr_field)
    df = df.groupby(aggr_field).agg(dict_pess)
    return df

In [19]:
aggr_fld = ['causa_acidente']

df1 = _acidentes(dfacid, aggr_fld, dictio)
df1

,causa_acidente,qtd,ilesos,feridos_leves,feridos_graves,mortos,percentual_mortalidade
74,TRANSITAR NA CONTRAMÃO,43,11,11,11,9,20.930233
4,ACUMULO DE ÁGUA SOBRE O PAVIMENTO,25,8,12,1,4,16.0
17,CONVERSÃO PROIBIDA,48,13,18,8,6,12.5
46,INGESTÃO DE SUBSTÂNCIAS PSICOATIVAS,9,4,2,1,1,11.111111
61,PEDESTRE ANDAVA NA PISTA,28,13,2,6,3,10.714286
...,...,...,...,...,...,...,...
43,FREAR BRUSCAMENTE,18,6,9,3,0,0.0
10,AUSÊNCIA DE SINALIZAÇÃO,2,0,2,0,0,0.0
45,ILUMINAÇÃO DEFICIENTE,4,1,1,2,0,0.0
6,AFUNDAMENTO OU ONDULAÇÃO NO PAVIMENTO,2,0,2,0,0,0.0
78,ÁREA URBANA SEM A PRESENÇA DE LOCAL APROPRIADO...,8,1,5,2,0,0.0

In [20]:
aggr_fld = ['tipo_acidente']
df1 = _acidentes(dfacid, aggr_fld, dictio)
df1

,tipo_acidente,qtd,ilesos,feridos_leves,feridos_graves,mortos,percentual_mortalidade
19,EVENTOS ATÍPICOS,12,3,6,2,1,8.333333
1,ATROPELAMENTO DE PEDESTRE,808,337,197,131,50,6.188119
10,COLISÃO FRONTAL,2084,121,135,124,86,4.126679
12,COLISÃO LATERAL MESMO SENTIDO,240,129,70,25,9,3.75
13,COLISÃO LATERAL SENTIDO OPOSTO,27,9,12,4,1,3.703704
23,SAÍDA DE LEITO CARROÇÁVEL,2381,716,1139,291,65,2.729945
22,QUEDA DE OCUPANTE DE VEÍCULO,652,54,446,124,12,1.840491
6,COLISÃO COM OBJETO EM MOVIMENTO,70,29,28,12,1,1.428571
5,COLISÃO COM OBJETO,164,43,81,26,2,1.219512
18,ENGAVETAMENTO,179,142,25,6,2,1.117318
7,COLISÃO COM OBJETO ESTÁTICO,639,268,257,63,7,1.095462
14,COLISÃO TRANSVERSAL,5240,515,407,174,36,0.687023
25,TOMBAMENTO,2453,197,468,116,14,0.57073
3,CAPOTAMENTO,2951,173,234,54,11,0.372755
15,COLISÃO TRASEIRA,16429,1230,763,211,55,0.334774
0,ATROPELAMENTO DE ANIMAL,1077,48,86,24,2,0.185701
16,DANOS EVENTUAIS,602,33,11,2,1,0.166113
11,COLISÃO LATERAL,8868,622,416,115,13,0.146594
9,COLISÃO COM OBJETO MÓVEL,478,0,0,0,0,0.0
17,DERRAMAMENTO DE CARGA,374,21,4,1,0,0.0
8,COLISÃO COM OBJETO FIXO,2622,0,0,0,0,0.0
4,COLISÃO COM BICICLETA,408,0,0,0,0,0.0
20,INCÊNDIO,410,161,6,1,0,0.0
21,QUEDA DE MOTOCICLETA / BICICLETA / VEÍCULO,1774,0,0,0,0,0.0
2,ATROPELAMENTO DE PESSOA,1832,0,0,0,0,0.0
24,SAÍDA DE PISTA,10334,0,0,0,0,0.0

In [21]:
aggr_fld = ['classificacao_acidente']
df1 = _acidentes(dfacid, aggr_fld, dictio)
df1

,classificacao_acidente,qtd,ilesos,feridos_leves,feridos_graves,mortos,percentual_mortalidade
0,Com Vítimas Fatais,802,132,58,74,368,45.885287
1,Com Vítimas Fatais,1767,0,0,0,0,0.0
2,Com Vítimas Feridas,29449,2633,4734,1432,0,0.0
3,Ignorado,67,0,0,0,0,0.0
4,Ignorado,335,0,0,0,0,0.0
5,Sem Vítimas,3407,2086,0,0,0,0.0
6,Sem Vítimas,27282,0,0,0,0,0.0

In [22]:
aggr_fld = ['fase_dia']
df1 = _acidentes(dfacid, aggr_fld, dictio)
df1

,fase_dia,qtd,ilesos,feridos_leves,feridos_graves,mortos,percentual_mortalidade
3,Plena Noite,4154,1622,1497,573,163,3.923929
1,Amanhecer,3286,224,225,79,22,0.669507
2,Anoitecer,3629,261,240,81,20,0.551116
5,Pleno dia,37314,2744,2830,773,163,0.436833
0,(null),4,0,0,0,0,0.0
4,Plena noite,14722,0,0,0,0,0.0

In [23]:
aggr_fld = ['tipo_pista']
df1 = _acidentes(dfacid, aggr_fld, dictio)
df1

,tipo_pista,qtd,ilesos,feridos_leves,feridos_graves,mortos,percentual_mortalidade
4,Simples,5584,1577,1766,643,198,3.545845
1,Dupla,9548,3211,2956,847,162,1.69669
3,Múltipla,973,63,70,16,8,0.822199
0,(null),1,0,0,0,0,0.0
2,Dupla,26714,0,0,0,0,0.0
5,Simples,20289,0,0,0,0,0.0

In [24]:
aggr_fld = ['tracado_via']
df1 = _acidentes(dfacid, aggr_fld, dictio)
df1

,tracado_via,qtd,ilesos,feridos_leves,feridos_graves,mortos,percentual_mortalidade
5,Interseção de vias,235,89,92,36,10,4.255319
6,Não Informado,1570,605,619,220,65,4.140127
4,Desvio Temporário,292,115,111,42,10,3.424658
11,Rotatória,73,32,27,11,2,2.739726
8,Reta,9899,3133,2925,869,219,2.212345
2,Curva,2968,739,929,300,59,1.987871
10,Retorno Regulamentado,192,101,63,16,3,1.5625
0,(null),1,0,0,0,0,0.0
1,Cruzamento,728,0,0,0,0,0.0
3,Curva,13064,0,0,0,0,0.0
7,Ponte,26,14,7,3,0,0.0
9,Reta,34007,0,0,0,0,0.0
12,Túnel,4,1,1,1,0,0.0
13,Viaduto,50,22,18,8,0,0.0

In [25]:
aggr_fld = ['uso_solo']
df1 = _acidentes(dfacid, aggr_fld, dictio)
df1

,uso_solo,qtd,ilesos,feridos_leves,feridos_graves,mortos,percentual_mortalidade
1,Não,6213,2300,2587,818,256,4.120393
4,Sim,5898,2551,2205,688,112,1.898949
0,(null),1,0,0,0,0,0.0
2,Rural,1577,0,0,0,0,0.0
3,Rural,26313,0,0,0,0,0.0
5,Urbano,23107,0,0,0,0,0.0

In [26]:
# Plotar o gráfico
#dfacid.plot(kind='bar', x='br', y='qtd')

In [27]:
# Análise estatística dos dados de acidentes
## Acidentes por UF
dfacid.describe()

              kmint           ano           mes
count  63109.000000  63109.000000  63109.000000
mean     412.864995   2012.707427      6.583181
std      255.583612      3.874534      3.500859
min        0.000000   2007.000000      1.000000
25%      115.000000   2010.000000      4.000000
50%      513.000000   2012.000000      7.000000
75%      601.000000   2015.000000     10.000000
max      773.000000   2021.000000     12.000000

In [28]:
dfacid.dtypes

id                         object
data_inversa               object
dia_semana                 object
horario                    object
uf                         object
br                         object
km                         object
kmint                     float64
municipio                  object
causa_acidente             object
tipo_acidente              object
classificacao_acidente     object
fase_dia                   object
sentido_via                object
condicao_metereologica     object
tipo_pista                 object
tracado_via                object
ilesos                     object
feridos_leves              object
feridos_graves             object
mortos                     object
uso_solo                   object
regional                   object
delegacia                  object
uop                        object
ano_mes                    object
ano                       float64
mes                       float64
latitude                   object
longitude                  object
dtype: object

### Plotar Mapa de Calor com tempo dos acidentes

In [46]:
###
# criar lista de ano_mes únicos
lista_index = df.ano_mes.unique()

print(lista_index)

lista_idx = []
for i in lista_index:
    lista_idx.append(i)

#print(lista_idx)
# -------------------------------------------

# criar a weight list
weight_list = []
dfacid['conta'] = 1
for x in dfacid['ano_mes'].sort_values().unique():
    weight_list.append(dfacid.loc[dfacid['ano_mes'] == x, ["latitude", "longitude", "conta"]].groupby(["latitude", "longitude"]).sum().reset_index().values.tolist()) 

# -------------------------------------------

# criar o mapa base
my_map = folium.Map(
                location=(
                            (dfacid.latitude.mean()),
                            (dfacid.longitude.mean())
                        ),
                zoom_start=6
            )

#folium.LayerControl().add_to(my_map)
folium.TileLayer('stamentoner').add_to(my_map)

# criar o mapa de calor de acidentes
HeatMapWithTime(weight_list, radius=10, index=lista_idx,
                gradient={0.1: 'blue', 0.25: 'yellow', 0.75:'orange', 1:'red'},
                auto_play=True, min_opacity=0.5, max_opacity=1, use_local_extrema=True).add_to(my_map)

my_map

['March/2007' 'January/2007' 'August/2007' 'September/2007' 'April/2007'
 'November/2007' 'October/2007' 'February/2007' 'June/2007'
 'December/2007' 'July/2007' 'May/2007' 'January/2008' 'July/2008'
 'December/2008' 'October/2008' 'November/2008' 'February/2008'
 'June/2008' 'May/2008' 'September/2008' 'August/2008' 'March/2008'
 'April/2008' 'April/2009' 'February/2009' 'June/2009' 'August/2009'
 'December/2009' 'January/2009' 'March/2009' 'May/2009' 'September/2009'
 'November/2009' 'July/2009' 'October/2009' 'April/2010' 'June/2010'
 'November/2010' 'December/2010' 'July/2010' 'January/2010' 'March/2010'
 'May/2010' 'August/2010' 'February/2010' 'October/2010' 'September/2010'
 'March/2011' 'June/2011' 'July/2011' 'April/2011' 'October/2011'
 'December/2011' 'August/2011' 'January/2011' 'May/2011' 'November/2011'
 'February/2011' 'September/2011' 'February/2012' 'May/2012' 'March/2012'
 'January/2012' 'April/2012' 'July/2012' 'November/2012' 'December/2012'
 'October/2012' 'August/2012' 'September/2012' 'June/2012' 'January/2013'
 'March/2013' 'April/2013' 'February/2013' 'July/2013' 'September/2013'
 'August/2013' 'October/2013' 'December/2013' 'May/2013' 'June/2013'
 'November/2013' 'March/2014' 'April/2014' 'December/2014' 'January/2014'
 'June/2014' 'July/2014' 'October/2014' 'February/2014' 'May/2014'
 'August/2014' 'November/2014' 'September/2014' 'January/2015'
 'March/2015' 'August/2015' 'October/2015' 'July/2015' 'February/2015'
 'May/2015' 'September/2015' 'November/2015' 'June/2015' 'April/2015'
 'December/2015' 'July/2016' 'September/2016' 'October/2016'
 'November/2016' 'January/2016' 'March/2016' 'April/2016' 'February/2016'
 'December/2016' 'May/2016' 'June/2016' 'August/2016' 'February/2017'
 'March/2017' 'April/2017' 'May/2017' 'June/2017' 'August/2017'
 'September/2017' 'October/2017' 'December/2017' 'January/2017'
 'July/2017' 'November/2017' 'January/2018' 'April/2018' 'July/2018'
 'August/2018' 'September/2018' 'February/2018' 'March/2018' 'May/2018'
 'June/2018' 'October/2018' 'November/2018' 'December/2018' 'January/2019'
 'March/2019' 'April/2019' 'June/2019' 'August/2019' 'September/2019'
 'October/2019' 'November/2019' 'December/2019' 'February/2019' 'May/2019'
 'July/2019' 'March/2020' 'April/2020' 'July/2020' 'August/2020'
 'October/2020' 'December/2020' 'January/2020' 'February/2020' 'May/2020'
 'June/2020' 'September/2020' 'November/2020' 'January/2021'
 'February/2021' 'March/2021' 'May/2021' 'June/2021' 'July/2021'
 'October/2021' 'April/2021' 'August/2021' 'September/2021'
 'November/2021' 'December/2021']

In [49]:

# criar o mapa base
m = folium.Map(
                location=(
                            (dfacid.latitude.mean()),
                            (dfacid.longitude.mean())
                        ),
                zoom_start=6
            )

mCluster = MarkerCluster(name="Markers Demo").add_to(m)

m
'''
for x in range(0, len(dfacid)):
    folium.Marker(location=[dfacid[x,:,dfacid.columns.get_loc('latitude')], dfacid[x,:,dfacid.columns.get_loc('longitude')]], 
                  popup="pnt - {0} e {1}".format(dfacid[x,:,dfacid.columns.get_loc('latitude')], dfacid[x,:,dfacid.columns.get_loc('longitude')])).add_to(mCluster)
'''

'\nfor x in range(0, len(dfacid)):\n    folium.Marker(location=[dfacid[x,:,dfacid.columns.get_loc(\'latitude\')], dfacid[x,:,dfacid.columns.get_loc(\'longitude\')]], \n                  popup="pnt - {0} e {1}".format(dfacid[x,:,dfacid.columns.get_loc(\'latitude\')], dfacid[x,:,dfacid.columns.get_loc(\'longitude\')])).add_to(mCluster)\n'

In [ ]:
'''
# criar o mapa base
m = folium.Map(
                location=(
                            (dfacid.latitude.mean()),
                            (dfacid.longitude.mean())
                        ),
                zoom_start=6
            )

#tooltip = "Click me!"
for idx, row in dfacid.iterrows():
    if pd.notnull(row["latitude"]): 
        folium.Marker([row["latitude"], row["longitude"]], popup="<i>acidente</i>").add_to(m)

m
'''

### Dataframe dos Veículos

In [ ]:
# Criar Dataframe com os veículos
dfveic = df[col_veiculos]
len(dfveic)

In [ ]:
dfveic

In [ ]:
# retirar as duplicações do veículos
dfveic = dfveic.drop_duplicates(subset=['id_veiculo'], keep='last')
# Total de registros únicos
len(dfveic)

In [ ]:
dfveic

In [ ]:
aggr_fld = ['tipo_veiculo']
df1 = _acidentes(dfveic, aggr_fld, dictio)
df1

### Dataframe das pessoas

In [ ]:
# Criar Dataframe com os veículos
dfpess = df[col_pessoas]
dfpess

In [ ]:
dfpess.describe()

In [ ]:
aggr_fld = ['tipo_envolvido', 'estado_fisico']
dict_pess={'tipo_envolvido':'count', 'idade':'mean'}
df = _acidente_pessoas(dfpess, aggr_fld, dict_pess)
df

## Regras de Associação - Apriori

Nesta seção vamos avaliar as regras de associação dos acidentes com o algoritmo Apriori.

### Preparação dos dados

Para execução do algoritmo, os dados devem ser transformados de DataFrame para Lista.

In [ ]:
# Fase 1... 
# Jogar os dados de acidentes em lista... somente campos a serem avaliados

# Vamos trabalhar com os seguintes campos: 
# 2   dia_semana
# 7   municipio
# 8   causa_acidente       
# 9   tipo_acidente      
# 10  classificacao_acidente       
# 11  fase_dia        
# 12  sentido_via      
# 13  condicao_metereologica       
# 14  tipo_pista       
# 15  tracado_via      
# 16  uso_solo     

col_apriori =  ['causa_acidente', 
                'tipo_acidente', 
                'fase_dia', 
                'condicao_metereologica', 
                'tipo_pista',
                'tracado_via',
                'classificacao_acidente']


df2apriori = dfacid[col_apriori]

acidentes = []
for i in range(0, len(df2apriori)):
#    print(i)
    acidentes.append([str(df2apriori.values[i,j]) for j in range(0,7)])
                     
#print(acidentes)

regras = apriori(acidentes, min_support = 0.15, min_confidence = 0.4, min_lift = 1, min_length=4)
#regras = apriori(acidentes)
resultados = list(regras)

resultados2 = [list(x) for x in resultados]
resultados2
print(len(resultados2))

resultadoFormatado = []
for j in range(0, 32):
    resultadoFormatado.append([list(x) for x in resultados2[j][2]])
    
resultadoFormatado

# TESTE CLUSTERING MAPA

In [ ]:
# IMPORTS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import seaborn as sns; sns.set()
import csv

In [ ]:
# CRIAR DATAFRAME
# Variable with the Longitude and Latitude
X=dfacid.loc[:,['id','latitude','longitude']]
X.dropna(subset=['latitude', 'longitude'], inplace=True)
X = X[(X.longitude >= -90)&(X.longitude <= 0)]
X

In [ ]:
K_clusters = range(1,10)
kmeans = [KMeans(n_clusters=i) for i in K_clusters]
Y_axis = X[['latitude']]
X_axis = X[['longitude']]
score = [kmeans[i].fit(Y_axis).score(Y_axis) for i in range(len(kmeans))]
# Visualize
plt.figure(figsize=(10,8))
plt.plot(K_clusters, score)
plt.xlabel('Number of Clusters')
plt.ylabel('Score')
plt.title('Elbow Curve')
plt.show()

In [ ]:
kmeans = KMeans(n_clusters = 10, init ='k-means++')
kmeans.fit(X[X.columns[1:3]]) # Compute k-means clustering.
X['cluster_label'] = kmeans.fit_predict(X[X.columns[1:3]])
centers = kmeans.cluster_centers_ # Coordinates of cluster centers.
labels = kmeans.predict(X[X.columns[1:3]]) # Labels of each point
X.head(10)

In [ ]:
#plt.figure(figsize =(20, 8))
plt.figure(figsize=(10,8))
X.plot.scatter(x = 'latitude', y = 'longitude', c=labels, s=50, cmap='plasma')
plt.scatter(centers[:, 0], centers[:, 1])

In [ ]:
X = X[['id','cluster_label']]

In [ ]:
clustered_data = X.merge(X, left_on='id', right_on='id')

In [ ]:
clustered_data

In [ ]:
#kkk = dfacid.query("(longitude <= float(-100))")
#dfb = dfacid.query("not (longitude >= 0 or longitude <0)")
#kkk = dfacid.drop[dfacid[(dfacid.longitude <= -90.0)]]

In [ ]:
Rodar até aqui

## Machine Learning - Classificação

In [ ]:
# Formato de matriz
previsores = df2apriori.iloc[:,0:6].values
classe = df2apriori.iloc[:,6].values
classe2 = df2apriori.iloc[:,6].values

In [ ]:
classe

In [ ]:
previsores

In [ ]:
# Transformação dos atributos categóricos em atributos numéricos, passando o índice de cada coluna categórica
# Precisamos criar um objeto para cada atributo categórico, pois na sequência vamos executar o processo de encoding novamente para o registro de teste
# Se forem utilizados objetos diferentes, o número atribuído a cada valor poderá ser diferente, o que deixará o teste inconsistente
labelencoder1 = LabelEncoder()
previsores[:,0] = labelencoder1.fit_transform(previsores[:,0])

labelencoder2 = LabelEncoder()
previsores[:,1] = labelencoder2.fit_transform(previsores[:,1])

labelencoder3 = LabelEncoder()
previsores[:, 2] = labelencoder3.fit_transform(previsores[:, 2])

labelencoder4 = LabelEncoder()
previsores[:, 3] = labelencoder4.fit_transform(previsores[:, 3])

labelencoder5 = LabelEncoder()
previsores[:, 4] = labelencoder5.fit_transform(previsores[:, 4])

labelencoder6 = LabelEncoder()
previsores[:, 5] = labelencoder6.fit_transform(previsores[:, 5])

#labelencoder7 = LabelEncoder()
#previsores[:, 6] = labelencoder7.fit_transform(previsores[:, 6])

#labelencoder8 = LabelEncoder()
#previsores[:, 7] = labelencoder8.fit_transform(previsores[:, 7])
labelencoder8 = LabelEncoder()
classe[:] = labelencoder8.fit_transform(classe[:])

In [ ]:
classe2

In [ ]:
# Divisão da base de dados entre treinamento e teste (30% para testar e 70% para treinar)
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores,
                                                                  classe,
                                                                  test_size = 0.3,
                                                                  random_state = 0)
X_teste

In [ ]:
y_treinamento

In [ ]:
X_treinamento

In [ ]:
# Criação e treinamento do modelo (geração da tabela de probabilidades)
#naive_bayes = GaussianNB()
#naive_bayes.fit(X_treinamento, y_treinamento)

In [ ]:
# Previsões utilizando os registros de teste
#previsoes = naive_bayes.predict(X_teste)
#previsoes

In [ ]:
#geração da matriz de confusão e cálculo da taxa de acerto e erro
#confusao = confusion_matrix(y_teste, previsoes)
#confusao

In [ ]:
#taxa_acerto = accuracy_score(y_teste, previsoes)
#taxa_erro = 1 - taxa_acerto
#taxa_acerto

In [ ]:
# Visualização da matriz de confusão
# Warning interno da biblioteca yellowbrick, já esta na última versão (sem solução para o warning no momento)
v = ConfusionMatrix(GaussianNB())
v.fit(X_treinamento, y_treinamento)
v.score(X_teste, y_teste)
v.poof()

## k-means

In [ ]:
# Importação das bibliotecas
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [ ]:
# Carregamento da base de dados 
#iris = datasets.load_iris()
# visualização de quantos registros existem por classe
xx = df2apriori.to_numpy()

#iris
unicos, quantidade = np.unique(classe, return_counts = True)
unicos
#quantidade
#iris

In [ ]:
quantidade

In [ ]:
previsores

In [ ]:
cluster = KMeans(n_clusters = 3)
cluster.fit(previsores)

In [ ]:
# Visualização dos três centroides
centroides = cluster.cluster_centers_
centroides

In [ ]:
# Visualização dos grupos que cada registro foi associado
previsoes = cluster.labels_
previsoes

In [ ]:
# Contagem dos registros por classe
unicos2, quantidade2 = np.unique(previsoes, return_counts = True)
unicos2

In [ ]:
quantidade2

In [ ]:
classe

In [ ]:
previsoes

In [ ]:
# Geração da matriz de contingência para comparar os grupos com a base de dados
resultados = confusion_matrix(classe, previsoes)
#resultados

In [ ]:
# Geração do gráfico com os clusters gerados, considerando para um (previsoes 0, 1 ou 2)
# Usamos somente as colunas 0 e 1 da base de dados original para termos 2 dimensões
plt.scatter(previsores[previsoes == 0, 0], previsores[previsoes == 0, 1], 
            c = 'green', label = 'Com Vítimas Fatais')
plt.scatter(previsores[previsoes == 1, 0], previsores[previsoes == 1, 1], 
            c = 'red', label = 'Com Vítimas Feridas')
plt.scatter(previsores[previsoes == 2, 0], previsores[previsoes == 2, 1], 
            c = 'blue', label = 'Sem Vítimas')
plt.legend()

## Random Forest

In [ ]:
# Importação das bibliotecas
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Formato de matriz
previsores = df2apriori.iloc[:,0:6].values
classe = df2apriori.iloc[:,6].values
#classe2 = df2apriori.iloc[:,6].values

In [ ]:
previsores

In [ ]:
# Formato de matriz
previsores = df2apriori.iloc[:,0:6].values
classe = df2apriori.iloc[:,6].values
classe2 = df2apriori.iloc[:,6].values

In [ ]:
# Transformação dos atributos categóricos em atributos numéricos, passando o índice de cada atributo categórico
labelencoder = LabelEncoder()
previsores[:,0] = labelencoder.fit_transform(previsores[:,0])
previsores[:,1] = labelencoder.fit_transform(previsores[:,1])
previsores[:,2] = labelencoder.fit_transform(previsores[:,2])
previsores[:,3] = labelencoder.fit_transform(previsores[:,3])
previsores[:,4] = labelencoder.fit_transform(previsores[:,4])
previsores[:,5] = labelencoder.fit_transform(previsores[:,5])
#previsores[:,6] = labelencoder.fit_transform(previsores[:,6])
#previsores[:, 11] = labelencoder.fit_transform(previsores[:, 11])
#previsores[:, 13] = labelencoder.fit_transform(previsores[:, 13])
#previsores[:, 14] = labelencoder.fit_transform(previsores[:, 14])
#previsores[:, 16] = labelencoder.fit_transform(previsores[:, 16])
#previsores[:, 18] = labelencoder.fit_transform(previsores[:, 18])
#previsores[:, 19] = labelencoder.fit_transform(previsores[:, 19])

In [ ]:
# Divisão da base de dados entre treinamento e teste (30% para testar e 70% para treinar)
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores,
                                                                  classe,
                                                                  test_size = 0.3,
                                                                  random_state = 0)

In [ ]:
X_treinamento

In [ ]:
y_treinamento

In [ ]:
# Criação do modelo, treinamento, obtenção das previsões e da taxa de acerto
floresta = RandomForestClassifier(n_estimators = 100)
floresta.fit(X_treinamento, y_treinamento)

In [ ]:
# Visualização dos atributos principais
floresta.estimators_
#floresta.estimators_[1]

In [ ]:
previsoes = floresta.predict(X_teste)
confusao = confusion_matrix(y_teste, previsoes)
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto